spring.application.name=SpringEcom
spring.datasource.url=jdbc:postgresql://localhost:5432/ecom
spring.datasource.username=postgres
spring.jpa.hibernate.ddl-auto=update

# Allow larger image uploads (default is 1MB per file)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# OAuth2 Google Configuration
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
jwt.secretKey=
spring.datasource.password=
spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=